# Diccionario de correspondencia invertido: simplificado -> completo
diccionario_correspondencia1 = {
    'Bournemouth': 'AFC Bournemouth',
    'Arsenal': 'Arsenal FC',
    'Aston Villa': 'Aston Villa',
    'Barnsley': 'Barnsley FC',
    'Birmingham': 'Birmingham City',
    'Blackburn': 'Blackburn Rovers',
    'Blackpool': 'Blackpool FC',
    'Bolton': 'Bolton Wanderers',
    'Bradford': 'Bradford City',
    'Brentford': 'Brentford FC',
    'Brighton': 'Brighton & Hove Albion',
    'Burnley': 'Burnley FC',
    'Cardiff': 'Cardiff City',
    'Charlton': 'Charlton Athletic',
    'Chelsea': 'Chelsea FC',
    'Coventry': 'Coventry City',
    'Crystal Palace': 'Crystal Palace',
    'Derby': 'Derby County',
    'Everton': 'Everton FC',
    'Reading': 'FC Reading',
    'Fulham': 'Fulham FC',
    'Huddersfield': 'Huddersfield Town',
    'Hull': 'Hull City',
    'Ipswich': 'Ipswich Town',
    'Leeds': 'Leeds United',
    'Leicester': 'Leicester City',
    'Liverpool': 'Liverpool FC',
    'Luton': 'Luton Town',
    'Man City': 'Manchester City',
    'Man United': 'Manchester United',
    'Middlesbrough': 'Middlesbrough FC',
    'Newcastle': 'Newcastle United',
    'Norwich': 'Norwich City',
    "Nott'm Forest": 'Nottingham Forest',
    'Oldham': 'Oldham Athletic',
    'Portsmouth': 'Portsmouth FC',
    'QPR': 'Queens Park Rangers',
    'Sheffield United': 'Sheffield United',
    'Sheffield Wednesday': 'Sheffield Wednesday',
    'Southampton': 'Southampton FC',
    'Stoke': 'Stoke City',
    'Sunderland': 'Sunderland AFC',
    'Swansea': 'Swansea City',
    'Swindon': 'Swindon Town',
    'Tottenham': 'Tottenham Hotspur',
    'Watford': 'Watford FC',
    'West Brom': 'West Bromwich Albion',
    'West Ham': 'West Ham United',
    'Wigan': 'Wigan Athletic',
    'Wimbledon': 'Wimbledon FC (- 2004)',
    'Wolves': 'Wolverhampton Wanderers'
}

diccionario_correspondencia2 = {
    'AFC Bournemouth': 'AFC Bournemouth',
    'Arsenal Football Club': 'Arsenal FC',
    'Aston Villa Football Club': 'Aston Villa',
    'Blackburn Rovers Football Club': 'Blackburn Rovers',
    'Brighton & Hove Albion Football Club': 'Brighton & Hove Albion',
    'Burnley Football Club': 'Burnley FC',
    'Chelsea Football Club': 'Chelsea FC',
    'Crystal Palace Football Club': 'Crystal Palace',
    'Everton Football Club': 'Everton FC',
    'Leeds United Football Club': 'Leeds United',
    'Leicester City': 'Leicester City',
    'Liverpool Football Club': 'Liverpool FC',
    'Manchester City Football Club': 'Manchester City',
    'Manchester United Football Club': 'Manchester United',
    'Newcastle United Football Club': 'Newcastle United',
    'Nottingham Forest Football Club': "Nottingham Forest",
    'Sheffield United Football Club': 'Sheffield United',
    'Sheffield Wednesday Football Club': 'Sheffield Wednesday',
    'Sunderland Association Football Club': 'Sunderland AFC',
    'Tottenham Hotspur Football Club': 'Tottenham Hotspur',
    'West Bromwich Albion Football Club': 'West Bromwich Albion',
    'West Ham United Football Club': 'West Ham United',
    'Wolverhampton Wanderers Football Club': 'Wolverhampton Wanderers'
}

diccionario_correspondencia3 = {
    'Arsenal': 'Arsenal FC',
    'Aston Villa': 'Aston Villa',
    'Birmingham': 'Birmingham City',
    'Blackburn': 'Blackburn Rovers',
    'Blackpool': 'Blackpool FC',
    'Bolton': 'Bolton Wanderers',
    'Brighton': 'Brighton & Hove Albion',
    'Charlton': 'Charlton Athletic',
    'Chelsea': 'Chelsea FC',
    'Everton': 'Everton FC',
    'Fulham': 'Fulham FC',
    'Ipswich': 'Ipswich Town',
    'Liverpool': 'Liverpool FC',
    'Manchester City': 'Manchester City',
    'Manchester United': 'Manchester United',
    'Middlesbrough': 'Middlesbrough FC',
    'Newcastle': 'Newcastle United',
    'Norwich': 'Norwich City',
    'Oldham': 'Oldham Athletic',
    'Portsmouth': 'Portsmouth FC',
    'Southampton': 'Southampton FC',
    'Sunderland': 'Sunderland AFC',
    'Tottenham': 'Tottenham Hotspur',
    'West Brom': 'West Bromwich Albion',
    'West Ham': 'West Ham United',
    'Wigan': 'Wigan Athletic'
}
